/**
 * Câu hỏi thường gặp của deck Isuzu Việt Nam, chỉ lấy từ nội dung đề xuất (decks/isuzu-vietnam/content.vi.ts).
 * Dùng cho: gói tri thức của trợ lý Isuzu, câu trả lời soạn sẵn khi offline / hết ngân sách / lỗi API, và câu gợi ý.
 * Không chứa thông tin của khách hàng khác, không mô tả cách Isuzu đang làm hôm nay. `keywords` viết có dấu hoặc không đều được.
 */
import type { FaqItem } from "../types";

export const faq: FaqItem[] = [
  {
    id: "nha-may-sieu-thong-minh-la-gi",
    q: "Nhà máy siêu thông minh là gì?",
    a: "Đó là nhà máy mà mỗi lỗi, mỗi quyết định và kết quả đều trở thành dữ liệu học cho một **Mô hình AI Thế giới thực**. Nhà máy **tự học** từ mỗi lỗi và hành động khắc phục, **dự báo trước** lỗi sắp lặp lại, và **nhân rộng** bài học sang mọi công đoạn, dòng xe và nhà cung cấp. QA luôn là người quyết định.",
    section: "sieu-thong-minh",
    keywords: ["siêu thông minh", "là gì", "định nghĩa", "tự học", "dự báo trước", "nhân rộng"],
    suggested: true,
  },
  {
    id: "monozukuri",
    q: "Đề xuất liên quan thế nào đến Isuzu Monozukuri?",
    a: "Ba năng lực của Nhà máy siêu thông minh đi theo ba bậc của Isuzu Monozukuri: **không bỏ sót lỗi** ứng với Tự học, **không tạo ra lỗi** ứng với Dự báo trước, **không thể tạo ra lỗi** ứng với Nhân rộng. Nền của cả ba bậc là sản xuất theo tiêu chuẩn; nền của cả ba năng lực là một bản ghi đầy đủ cho từng chiếc xe. Mô hình hỗ trợ từng bậc, không thay thế phương pháp của Isuzu.",
    section: "sieu-thong-minh",
    keywords: ["monozukuri", "ba bậc", "không bỏ sót lỗi", "không tạo ra lỗi", "không thể tạo ra lỗi", "IMM"],
    suggested: true,
  },
  {
    id: "ly-lich-so",
    q: "Lý lịch số của một chiếc xe là gì?",
    a: "Là bản ghi nối mọi thứ liên quan tới một VIN: trạm, đồ gá, người thao tác, ca, linh kiện, serial, nhà cung cấp, lô, kết quả QC và vị trí hiện tại của xe. Từ một lỗi, mô hình nối được toàn bộ bối cảnh; từ một chiếc xe, biết xe được lắp từ những gì; từ một lô linh kiện, biết lô đó nằm trên những xe nào và mỗi xe đang ở nhà máy, đại lý hay khách hàng.",
    section: "ly-lich-so",
    keywords: ["lý lịch", "gia phả", "lý lịch số", "VIN", "genealogy", "ký ức", "bản ghi"],
    suggested: true,
  },
  {
    id: "truy-xuat-hai-chieu",
    q: "Truy xuất hai chiều nghĩa là gì?",
    a: "Chiều thứ nhất: từ một VIN biết xe lắp động cơ, cầu, phanh, kính, ghế nào, với serial, nhà cung cấp và lô. Chiều thứ hai: khi nhà cung cấp báo một lô có vấn đề, mô hình lập ngay danh sách mọi VIN đã lắp lô đó, kèm ngày sản xuất, kết quả QC và vị trí hiện tại. Tiêu chí đạt trong Pilot là khớp **100%** với hồ sơ đối chiếu do QA chọn.",
    section: "ly-lich-so",
    keywords: ["truy xuất", "hai chiều", "lô", "nhà cung cấp", "triệu hồi", "khoanh vùng"],
  },
  {
    id: "ai-co-thay-qa-khong",
    q: "AI có thay QA quyết định chất lượng không?",
    a: "Không. Mô hình chỉ tìm, dự báo và so sánh: tìm ca cũ, tìm điểm chung, tìm hành động khắc phục, khoanh vùng xe bị ảnh hưởng. **QA phê duyệt mọi quyết định chất lượng**, mọi thay đổi tiêu chuẩn và mọi quyết định xuất xưởng. Mô hình không điều khiển thiết bị và không tự giữ hay cho xuất xưởng một chiếc xe nào.",
    section: "ba-lop",
    keywords: ["thay qa", "quyết định", "xuất xưởng", "tự động", "điều khiển", "giữ xe"],
    suggested: true,
  },
  {
    id: "phan-quyen-chat-luong",
    q: "Mô hình có làm thay đổi cách phân quyền giữa các bộ phận không?",
    a: "Không. Kỹ thuật sản xuất, Sản xuất và QC vẫn độc lập và giám sát lẫn nhau như hiện nay. Mô hình là nguồn bằng chứng chung cho cả ba bên; quyền kết luận về chất lượng vẫn thuộc QC.",
    section: "ba-lop",
    keywords: ["phân quyền", "kỹ thuật sản xuất", "QC", "độc lập", "giám sát lẫn nhau"],
  },
  {
    id: "vi-sao-bat-dau-tu-body",
    q: "Vì sao bắt đầu từ công đoạn BODY?",
    a: "BODY là nơi lỗi được phát hiện sớm nhất và vòng phản hồi ngắn nhất: lỗi phát hiện trong ca, khắc phục được kiểm chứng trong vài ngày. Dữ liệu cần thiết đã có (hồ sơ lỗi, nguyên nhân, khắc phục, nội dung Asakai), không cần lắp thêm cảm biến. Lỗi chặn được ở BODY không đi tiếp qua PAINT, TRIM, CHASSIS. Phạm vi cụ thể sẽ được chốt cùng QA, Kỹ thuật sản xuất và Sản xuất trong khảo sát.",
    section: "ban-do",
    keywords: ["body", "bắt đầu", "vì sao", "công đoạn đầu", "cabin", "QKR"],
    suggested: true,
  },
  {
    id: "asakai",
    q: "Hệ thống hỗ trợ Asakai thế nào?",
    a: "Trước Asakai mỗi sáng, một bản tóm tắt đã sẵn: lỗi hôm qua, lỗi nào khớp với ca cũ, hành động khắc phục nào đang chờ kết quả. Cuộc họp bắt đầu từ quyết định, không từ việc tổng hợp. Quyết định trong cuộc họp được gắn vào từng VIN liên quan và quay về mô hình.",
    section: "mot-ngay",
    keywords: ["asakai", "họp sáng", "tóm tắt", "đầu ngày"],
  },
  {
    id: "thay-the-he-thong",
    q: "Celesnity có thay thế hệ thống đang dùng không?",
    a: "Không. Celesnity **không thay thế hệ thống nào**. Pilot chỉ đọc dữ liệu đã có, không lắp thêm cảm biến, không thay hệ thống hiện tại. Mô hình nối dữ liệu từ các nguồn hiện có bằng VIN và trả lời những câu hỏi cắt ngang nhiều nguồn. Hệ thống cụ thể nào được kết nối sẽ được xác định trong khảo sát.",
    section: "hai-con-duong",
    keywords: ["thay thế", "hệ thống hiện có", "erp", "mes", "tích hợp", "cảm biến"],
    suggested: true,
  },
  {
    id: "khac-cong-cu-ai",
    q: "Khác gì so với việc thêm công cụ AI cho từng bộ phận?",
    a: "Mỗi công cụ riêng giữ một phần dữ liệu và hiểu một lỗi trong phạm vi nó nhìn thấy. Một mô hình chung nối mọi dữ liệu bằng VIN, nên cùng một lỗi được nối tới trạm, đồ gá, lô linh kiện, ca và mọi xe liên quan. Bài học thành trí thông minh chung, và lý lịch đi theo xe đến đại lý và khách hàng.",
    section: "hai-con-duong",
    keywords: ["công cụ riêng", "khác gì", "từng bộ phận", "một mô hình chung"],
  },
  {
    id: "mo-hinh-ai-the-gioi-thuc",
    q: "Mô hình AI Thế giới thực khác gì chatbot?",
    a: "Chatbot đọc, viết và trả lời câu hỏi. **Mô hình AI Thế giới thực** học cách một hệ thống vật lý phản ứng với quyết định và dự báo trước, kèm mức độ chắc chắn, và nói \"không biết\" khi gặp tình huống chưa từng thấy. Mô hình ngôn ngữ chỉ dùng để hiểu câu hỏi và giải thích.",
    section: "ky-nguyen",
    keywords: ["world model", "mô hình ai thế giới thực", "chatbot", "khác gì", "chatgpt"],
  },
  {
    id: "ba-lop",
    q: "Ba lớp của hệ thống gồm những gì?",
    a: "Lớp ① là nền tảng Minder, \"trí nhớ của nhà máy\": lý lịch số cho từng VIN, báo lỗi bằng giọng nói tiếng Việt, phân quyền. Lớp ② là Mô hình AI Thế giới thực, học quan hệ giữa lỗi, trạm, đồ gá, lô, ca, dòng xe. Lớp ③ là Tác nhân AI: Tác nhân Chất lượng và Tác nhân Truy xuất. QA và người có thẩm quyền phê duyệt.",
    section: "ba-lop",
    keywords: ["ba lớp", "kiến trúc", "minder", "tác nhân", "nền tảng"],
  },
  {
    id: "du-lieu-roi-vn",
    q: "Dữ liệu có ra khỏi Việt Nam hay gửi về nước ngoài không?",
    a: "Dữ liệu thô lưu tại Việt Nam, dưới quyền Isuzu. Bản vẽ, thông số kỹ thuật, tài liệu CKD và tiêu chuẩn của Isuzu Motors **không bao giờ rời Isuzu**. Isuzu duyệt mục đích, người truy cập, thời hạn lưu và mọi phần được chia sẻ. Pilot chạy ở Mức 1: không có gì rời môi trường Isuzu. Mọi kết nối với hệ thống hay tiêu chuẩn của Isuzu Motors theo quy định của Isuzu.",
    section: "hop-tac",
    keywords: ["dữ liệu", "việt nam", "nước ngoài", "nhật", "rời", "bảo mật", "cloud"],
    suggested: true,
  },
  {
    id: "du-lieu-nguoi-thao-tac",
    q: "Thông tin người thao tác được dùng thế nào?",
    a: "Chỉ để phân tích quy trình, ví dụ một lỗi có tập trung ở một ca hay một đồ gá hay không. Thông tin người thao tác **không bao giờ** được dùng để xếp hạng hay kỷ luật cá nhân. Người lao động được tham vấn trước và dữ liệu được khử nhận diện.",
    section: "hop-tac",
    keywords: ["người thao tác", "công nhân", "giám sát", "kỷ luật", "cá nhân", "operator"],
  },
  {
    id: "bo-de-thi",
    q: "Bộ đề thi kín hoạt động thế nào?",
    a: "QA Isuzu giữ riêng một phần lịch sử lỗi kèm kết quả thật. Celesnity không xem được đáp án; mô hình làm bài, Isuzu chấm. Mô hình chỉ thấy thông tin có tại thời điểm của mỗi lỗi cũ. Mô hình phải thi đạt trên dữ liệu của chính Isuzu trước khi được dùng.",
    section: "lo-trinh",
    keywords: ["đề thi", "bộ đề", "chấm", "kiểm chứng", "thi trên lịch sử"],
    suggested: true,
  },
  {
    id: "khong-hon-cach-hien-tai",
    q: "Nếu mô hình không tốt hơn cách làm hiện tại thì sao?",
    a: "Cổng 2 ở tháng 4 chấm mô hình trên bộ đề kín. Không đạt thì dừng hoặc điều chỉnh use case đó, và **không chuyển sang giai đoạn có phí tiếp theo khi cổng chưa đạt**. Kể cả khi Pilot không đạt, Isuzu vẫn giữ dữ liệu lỗi đã được làm sạch và nối theo VIN, quy trình hồ sơ lỗi tự động, bộ đề thi kín và đội IT đã được đào tạo.",
    section: "hai-ben",
    keywords: ["không đạt", "thất bại", "không hơn", "rủi ro", "dừng", "không có gì để mất"],
  },
  {
    id: "cac-cong",
    q: "Các cổng đánh giá gồm những gì?",
    a: "Có bốn cổng:\n- **Cổng 1 (T1):** dữ liệu đủ để làm, thỏa thuận dữ liệu đã ký, hồ sơ lỗi tự động chạy trên chuyền.\n- **Cổng 2 (T4):** ≥80% lỗi trong bộ đề có ca đúng trong 5 kết quả đầu; truy xuất khớp 100%; IT Isuzu tự chạy 1 vòng.\n- **Cổng 3 (T8):** ≥20 ca thật dùng kết quả của mô hình; IT Isuzu tự vận hành 4 tuần.\n- **Cổng 4 (T12):** Tài chính xác nhận giá trị ≥ ngưỡng hòa vốn; IT Isuzu tự huấn luyện lại.\nCác ngưỡng là đề xuất, chốt sau khảo sát.",
    section: "lo-trinh",
    keywords: ["cổng", "ngưỡng", "tiêu chí đạt", "gate", "cổng 2"],
  },
  {
    id: "pilot-16-tuan",
    q: "Pilot 16 tuần gồm những gì?",
    a: "Tuần 1–2 khảo sát công đoạn BODY và ký thỏa thuận dữ liệu. Tuần 3–4 dựng môi trường tại Việt Nam, xây từ điển lỗi và bật hồ sơ lỗi tự động (Cổng 1). Tuần 5–8 nối 2 năm lịch sử và dựng bộ đề thi kín. Tuần 9–12 thi trên lịch sử của chính Isuzu. Tuần 13–14 chạy song song, đưa kết quả vào Asakai. Tuần 15–16 Tài chính xác nhận giá trị, báo cáo trước Ban chỉ đạo (Cổng 2).",
    section: "lo-trinh",
    keywords: ["pilot", "16 tuần", "thử nghiệm", "kế hoạch", "tuần"],
  },
  {
    id: "isuzu-can-lam-gi",
    q: "Isuzu cần chuẩn bị những gì?",
    a: "Chỉ ba việc:\n- **Mở dữ liệu đã có:** chỉ đọc, không lắp thêm cảm biến, không thay hệ thống hiện tại.\n- **Cử người:** 2 kỹ sư IT, và chuyên gia QA/Kỹ thuật sản xuất khoảng 4 giờ/tuần.\n- **Giữ đề thi và chấm điểm.**",
    section: "lo-trinh",
    keywords: ["chuẩn bị", "cần làm gì", "nhân sự", "nguồn lực", "cử người", "IT"],
  },
  {
    id: "doi-it-isuzu",
    q: "Đội IT Isuzu sẽ tự vận hành hệ thống từ khi nào?",
    a: "IT Isuzu tự chạy một vòng dữ liệu ở T4, tự vận hành 4 tuần liên tục ở T8, và tự huấn luyện lại mô hình riêng ở T12. Tỷ lệ vận hành chuyển từ Celesnity 90% trong Pilot sang Isuzu 80% trong giai đoạn Nhân rộng. Năm 2, đội Isuzu dẫn dắt pilot hậu mãi, Celesnity hỗ trợ.",
    section: "lo-trinh",
    keywords: ["tự vận hành", "chuyển giao", "IT", "đội isuzu", "tự chủ", "hitozukuri"],
  },
  {
    id: "dai-ly-hau-mai",
    q: "Đề xuất có liên quan đến đại lý và hậu mãi không?",
    a: "Có, đó là đích đến. Lý lịch số đi theo xe ra khỏi nhà máy: khi có một lô nghi vấn, biết xe nào của khách hàng cần kiểm tra; khi xe vào xưởng, kỹ thuật viên biết nên chuẩn bị gì. Phần ngoài cổng nhà máy là **hướng đề xuất**, được khảo sát từ T10 và xác định cùng Isuzu sau khi có kết quả trong nhà máy.",
    section: "ban-do",
    keywords: ["đại lý", "hậu mãi", "dịch vụ", "củ chi", "khách hàng", "uptime"],
  },
  {
    id: "lo-trinh-12-thang",
    q: "Sau 12 tháng Isuzu có gì?",
    a: "6 use case chạy thật · đủ 5 công đoạn BODY, PAINT, TRIM, CHASSIS, QC · lý lịch số cho mọi VIN mới · **đội IT Isuzu tự vận hành mô hình** · kế hoạch pilot hậu mãi cho năm 2.",
    section: "lo-trinh",
    keywords: ["12 tháng", "kết quả", "sau một năm", "lộ trình"],
  },
  {
    id: "su-dung-giong-noi",
    q: "Công nhân báo lỗi bằng cách nào?",
    a: "Công nhân nói một câu bằng tiếng Việt, ví dụ \"Trạm BODY-08, xe QKR-00182 bản lề cửa phải bị lệch, lô LOT-2938\". AI tự tạo hồ sơ, gắn VIN, trạm, linh kiện, lô, đồ gá, ca và nêu thông tin còn thiếu. Phần demo tại Công đoạn BODY cho thấy Minder vận hành trên dữ liệu mô phỏng của nhà máy.",
    section: "thu-ngay",
    keywords: ["giọng nói", "báo lỗi", "công nhân", "nói", "hồ sơ", "thử"],
  },
  {
    id: "phi",
    q: "Chi phí Pilot là bao nhiêu?",
    a: "Phí Pilot là phí cố định, thống nhất sau khảo sát công đoạn BODY. Sau Pilot, định giá theo giá trị Tài chính Isuzu đã xác minh; mỗi công đoạn, dòng xe hay phạm vi ngoài nhà máy được định giá riêng. Không đạt Cổng 2 thì không chuyển sang giai đoạn có phí tiếp theo.",
    section: "hop-tac",
    keywords: ["giá", "phí", "chi phí", "báo giá", "bao nhiêu tiền", "ngân sách"],
  },
  {
    id: "gia-tri",
    q: "Giá trị được đo thế nào?",
    a: "Giá trị được đo trên mỗi chiếc xe và **Tài chính Isuzu là người xác nhận**. Các nguồn giá trị: giờ kỹ sư được giải phóng, ít lỗi lặp lại, khoanh vùng hẹp và nhanh khi có lô nghi vấn, ít dừng chuyền ngoài kế hoạch, đúng linh kiện đúng lúc. Con số cụ thể được Tài chính Isuzu điền sau Cổng 1; đề xuất không đưa con số giả định về lợi ích.",
    section: "hop-tac",
    keywords: ["giá trị", "roi", "lợi ích", "hòa vốn", "tiết kiệm", "đo"],
  },
  {
    id: "muc-tham-gia",
    q: "Ba mức tham gia khác nhau thế nào?",
    a: "Mức 1 (Riêng): không có gì rời môi trường Isuzu. Mức 2 (Đóng góp): chỉ bản cập nhật mô hình đã qua kiểm thử bảo mật. Mức 3 (Đối tác sáng lập): thêm tập dữ liệu kiểm chứng đã khử nhận diện, duyệt từng bản ghi, đổi lại quyền dùng mô hình nền lâu hơn, tính năng mới sớm 6 tháng và chủ trì Ban chỉ đạo. **Pilot chạy ở Mức 1**; Isuzu chọn mức chính thức sau khi xem kết quả Cổng 2.",
    section: "hop-tac",
    keywords: ["mức tham gia", "mức 1", "mức 2", "mức 3", "đối tác sáng lập", "đóng góp"],
  },
  {
    id: "so-huu-tri-tue",
    q: "Ai sở hữu mô hình và dữ liệu?",
    a: "Dữ liệu, bản vẽ, hồ sơ sản xuất và lý lịch số thuộc Isuzu. Mô hình riêng và các kết quả về hoạt động của Isuzu thuộc Isuzu; Celesnity chỉ dùng để vận hành dịch vụ. Mô hình nền và bộ công cụ đánh giá thuộc Celesnity; Isuzu có giấy phép nội bộ vĩnh viễn, miễn phí bản quyền theo mức tham gia. Mã nguồn và mô hình riêng được lưu ký tại bên thứ ba.",
    section: "hop-tac",
    keywords: ["sở hữu", "sở hữu trí tuệ", "IP", "mô hình", "lưu ký", "giấy phép"],
  },
  {
    id: "phap-ly",
    q: "Đề xuất tuân thủ những quy định pháp lý nào?",
    a: "Luật Trí tuệ nhân tạo 134/2025/QH15 (hiệu lực 1/3/2026), Nghị định 142/2026/NĐ-CP, Quyết định 33/2026/QĐ-TTg và Luật Bảo vệ dữ liệu cá nhân 91/2025/QH15 cùng Nghị định 356/2025/NĐ-CP. Celesnity lập hồ sơ phân loại rủi ro cho từng chức năng. An ninh theo kiến trúc nhà máy đã duyệt và mô hình phân vùng IEC 62443, bắt đầu ở chế độ chỉ đọc.",
    section: "hop-tac",
    keywords: ["pháp lý", "luật", "luật trí tuệ nhân tạo", "dữ liệu cá nhân", "IEC 62443", "an ninh"],
  },
  {
    id: "rui-ro",
    q: "Những rủi ro chính và cách xử lý?",
    a: "- Dữ liệu chưa nối được tới VIN hoặc lô: Cổng 1 kiểm tra trước; bắt đầu theo lô khi chưa có theo VIN.\n- Mô hình nhầm trùng hợp thành nguyên nhân: thi trên lỗi cũ, QA chấm, chỉ dùng ở chế độ tư vấn.\n- Kinh nghiệm ở BODY không áp dụng được cho công đoạn khác: mỗi công đoạn có bộ đề riêng.\n- Phụ thuộc vào Celesnity: IT Isuzu tự vận hành từ T8, tự huấn luyện từ T12; mã nguồn được lưu ký.",
    section: null,
    keywords: ["rủi ro", "risk", "xử lý", "phụ thuộc", "trùng hợp"],
  },
  {
    id: "lien-he",
    q: "Bước tiếp theo là gì?",
    a: "Celesnity kính đề nghị Ban Tổng Giám đốc ba việc: thống nhất chủ trương, cử nhân sự (lãnh đạo phụ trách, đầu mối QA, Kỹ thuật sản xuất, IM Promotion, dữ liệu, Tài chính và 2 kỹ sư IT), và cho phép khảo sát công đoạn BODY trong tháng 11/2026 để chốt dòng xe, bài toán, số nền và phí Pilot.",
    section: "thu-ngo",
    keywords: ["bước tiếp theo", "liên hệ", "bắt đầu", "đề nghị", "khảo sát"],
  },
];
