/**
 * Câu hỏi thường gặp của deck Nestlé Trị An, chỉ lấy từ nội dung đề xuất (decks/nestle-vietnam/content.vi.ts).
 * Dùng cho: gói tri thức của trợ lý Nestlé, câu trả lời soạn sẵn khi offline / hết ngân sách / lỗi API, và câu gợi ý.
 * Không chứa thông tin của khách hàng khác. `keywords` viết có dấu hoặc không đều được.
 */
import type { FaqItem } from "../types";

export const faq: FaqItem[] = [
  {
    id: "nha-may-sieu-thong-minh-la-gi",
    q: "Nhà máy siêu thông minh là gì?",
    a: "Đó là nhà máy mà kế hoạch, vận hành và phục hồi chạy trên cùng một **Mô hình AI Thế giới thực**. Nhà máy **tự học** từ mỗi kế hoạch và kết quả, **dự báo trước** hệ quả của một quyết định trước khi làm, và **nhân rộng** kinh nghiệm sang dây chuyền và nhà máy khác. Con người luôn là người quyết định.",
    section: "sieu-thong-minh",
    keywords: ["siêu thông minh", "là gì", "định nghĩa", "tự học", "dự báo trước", "nhân rộng"],
    suggested: true,
  },
  {
    id: "vi-sao-dolce-gusto",
    q: "Vì sao bắt đầu từ dây chuyền NESCAFÉ Dolce Gusto?",
    a: "Một dây chuyền viên nén có đủ các loại quyết định: kế hoạch, chuyển đổi SKU, môi trường phòng kiểm soát, chất lượng và đóng gói. Dây chuyền hiện đại nên phần lớn thời gian thử nghiệm dành cho bài toán, không cho lắp đặt. Sản phẩm xuất khẩu nên kết quả đo được bằng đơn vị rõ ràng.",
    section: "ban-do",
    keywords: ["dolce gusto", "bắt đầu", "vì sao", "dây chuyền đầu tiên", "viên nén"],
    suggested: true,
  },
  {
    id: "thay-the-he-thong",
    q: "Celesnity có thay thế MES, SAP hay SCADA không?",
    a: "Không. Celesnity **không thay thế bất kỳ hệ thống nào đang vận hành**. Mô hình đọc dữ liệu (chỉ đọc) từ chính các hệ thống hiện có của nhà máy Nestlé Trị An và trả lời những câu hỏi mà từng hệ thống riêng lẻ chưa trả lời được: một sự việc ảnh hưởng thế nào đến lô, kế hoạch, đơn hàng, và bước xử lý tiếp theo nên là gì.",
    section: "hai-con-duong",
    keywords: ["mes", "sap", "scada", "thay thế", "hệ thống hiện có", "historian", "tích hợp"],
    suggested: true,
  },
  {
    id: "khac-cong-cu-ai",
    q: "Khác gì so với việc thêm từng công cụ AI riêng lẻ?",
    a: "Mỗi công cụ riêng chỉ thấy một phần của nhà máy, nên cảnh báo độ ẩm chỉ đến khi đã vượt ngưỡng và dừng lại trong công cụ cảnh báo. Một mô hình chung thấy cả AHU, lô, kế hoạch và đơn hàng, nên độ ẩm được **dự báo trước** khi vượt ngưỡng, tác động lên lô và kế hoạch được tính sẵn, và có các phương án xử lý trước.",
    section: "hai-con-duong",
    keywords: ["công cụ riêng lẻ", "khác gì", "dashboard", "cảnh báo", "một mô hình chung"],
  },
  {
    id: "mo-hinh-the-gioi-thuc",
    q: "Mô hình AI Thế giới thực khác chatbot như thế nào?",
    a: "Chatbot đọc và trả lời từ tài liệu. **Mô hình AI Thế giới thực** học cách dây chuyền phản ứng với quyết định và sự cố, rồi dự báo hệ quả của một phương án trước khi làm, kèm mức độ chắc chắn. Mô hình nói \"chưa đủ dữ liệu\" khi gặp tình huống chưa có dữ liệu, không bịa ra kết quả.",
    section: "ba-lop",
    keywords: ["world model", "chatbot", "mô hình ai thế giới thực", "khác gì", "llm"],
  },
  {
    id: "ba-lop",
    q: "Hệ thống gồm những lớp nào?",
    a: "Ba lớp: **Nền tảng dữ liệu** ghi lại và đồng bộ dữ liệu từ MES, historian, ERP, QMS, bảo trì; **Mô hình AI Thế giới thực** dự báo; **Tác nhân AI** soạn kế hoạch, truy vết và phương án. Con người có thẩm quyền phê duyệt mọi kế hoạch, phương án và quyết định chất lượng.",
    section: "ba-lop",
    keywords: ["ba lớp", "kiến trúc", "tác nhân ai", "nền tảng dữ liệu", "agent"],
  },
  {
    id: "lich-san-xuat-llm",
    q: "Ai tạo ra lịch sản xuất, mô hình ngôn ngữ hay bộ giải?",
    a: "Lịch sản xuất do **bộ giải tối ưu có ràng buộc** tạo ra, và mọi phương án vi phạm ràng buộc bắt buộc đều bị loại. Mô hình dự báo kết quả của từng lịch. Mô hình ngôn ngữ chỉ hiểu câu hỏi và giải thích kết quả, **không tự nghĩ ra lịch**. Bộ phận Kế hoạch là người duyệt.",
    section: "use-case",
    keywords: ["lịch sản xuất", "bộ giải", "solver", "tối ưu", "kế hoạch tuần", "llm"],
  },
  {
    id: "su-co-do-am",
    q: "Khi độ ẩm phòng chiết rót tăng, hệ thống làm gì?",
    a: "Ứng dụng 3 xử lý theo hai bước. **Trước khi vượt ngưỡng:** mô hình dự báo độ ẩm và trạng thái AHU, cảnh báo sớm cho Bảo trì và Trưởng ca kèm checklist, và đề xuất cửa sổ bảo trì ít ảnh hưởng kế hoạch nhất. **Nếu vẫn vượt ngưỡng:** AI tự mở hồ sơ sự cố, gắn lô, mẻ và SKU để QA quyết định, tính tác động và chuyển sang Ứng dụng 1 để điều chỉnh kế hoạch. AI không điều khiển AHU hay dừng dây chuyền.",
    section: "thu-ngay",
    keywords: ["độ ẩm", "phòng chiết rót", "phòng kiểm soát", "sự cố", "humidity", "ahu", "phục hồi", "lô bị ảnh hưởng"],
    suggested: true,
  },
  {
    id: "nguong-ai-dat",
    q: "Ngưỡng độ ẩm và quyết định xử lý lô có do AI đặt không?",
    a: "Không. Ngưỡng, giới hạn và quy tắc xử lý lấy từ **tiêu chuẩn của nhà máy**. Quyết định QA và xuất lô giữ nguyên quyền hiện tại; mô hình chỉ nêu bằng chứng và đề xuất.",
    section: "thu-ngay",
    keywords: ["ngưỡng", "qa", "xuất lô", "quyết định lô", "tiêu chuẩn nhà máy"],
  },
  {
    id: "ba-use-case",
    q: "Giai đoạn đầu gồm những ứng dụng nào?",
    a: "- Nền tảng dữ liệu · Báo cáo ca, ngày, tuần (dùng thật từ T+1)\n- Ứng dụng 1 · Tự động lập báo cáo và kế hoạch (T+6)\n- Ứng dụng 2 · Đo lường hao hụt tự động (T+6)\n- Ứng dụng 3 · Cảnh báo sớm rủi ro môi trường sản xuất (T+5)\n- Cả ba chạy trên cùng một **Mô hình AI Thế giới thực**, theo quy trình Kế hoạch → Vận hành → Dự báo trước và Phục hồi",
    section: "use-case",
    keywords: ["use case", "ứng dụng", "ba use case", "danh mục", "giai đoạn đầu", "ưu tiên"],
    suggested: true,
  },
  {
    id: "hao-hut",
    q: "Ứng dụng hao hụt bột làm gì?",
    a: "Ứng dụng 2 tính **cân bằng bột** cho từng ca, từng lô từ dữ liệu máy: bột cấp vào, số viên đạt, viên bị loại ở cân kiểm, khối lượng từng viên. Hao hụt được tách theo nguyên nhân (định lượng dư, viên loại, xả khi chuyển đổi, vệ sinh) và tự điền vào báo cáo ca. Mô hình học mức hao hụt bình thường để chỉ ra ca lệch. Vẫn cần cân đối chiếu định kỳ; Sản xuất và QA quyết định mọi điều chỉnh định lượng.",
    section: "use-case",
    keywords: ["hao hụt", "bột", "định lượng", "giveaway", "lượng dư", "khối lượng tịnh", "cân kiểm", "cân bằng vật chất"],
  },
  {
    id: "bao-tri-du-doan",
    q: "Có phải là bảo trì dự đoán không?",
    a: "Ứng dụng 3 không thay hệ thống giám sát thiết bị hay báo động hiện có. Nó dự báo độ ẩm phòng chiết rót từ trạng thái AHU, chiller, thời tiết và tải dây chuyền, rồi đề xuất cửa sổ bảo trì ít ảnh hưởng nhất đến kế hoạch tuần. Bảo trì và Trưởng phòng Sản xuất là người quyết định.",
    section: "use-case",
    keywords: ["bảo trì", "predictive maintenance", "bảo trì dự đoán", "cửa sổ bảo trì", "giám sát thiết bị", "ahu"],
  },
  {
    id: "lo-trinh-12-thang",
    q: "Lộ trình 12 tháng diễn ra thế nào?",
    a: "Bốn giai đoạn: **Thử nghiệm** (T+1–T+4): nền dữ liệu dùng thật, ba ứng dụng thi trên dữ liệu lịch sử với bộ đề thi kín; **Triển khai** (T+5–T+8): ba ứng dụng dùng thật và được nối thành một quy trình; **Nhân rộng** (T+9–T+12) ra toàn nhà máy Trị An với một kế hoạch chung; **Năm thứ 2**, Đội ngũ IT của nhà máy Trị An dẫn dắt nhân rộng sang nhà máy Nestlé thứ hai.",
    section: "lo-trinh",
    keywords: ["lộ trình", "12 tháng", "giai đoạn", "timeline", "kế hoạch triển khai"],
    suggested: true,
  },
  {
    id: "thu-nghiem-16-tuan",
    q: "Thử nghiệm 16 tuần gồm những bước nào?",
    a: "Tuần 1–2 khảo sát, chốt chỉ số, số liệu nền và mục tiêu của ba ứng dụng; tuần 3–4 dựng môi trường, kết nối chỉ đọc và bật nền dữ liệu với báo cáo ca (Cổng 1); tuần 5–8 nối dữ liệu lịch sử, Nestlé dựng bộ đề thi kín; tuần 9–12 thi trên dữ liệu lịch sử của nhà máy Trị An; tuần 13–14 chạy song song trên ca thật; tuần 15–16 bộ phận Tài chính xác nhận cách đo giá trị (Cổng 2).",
    section: "lo-trinh",
    keywords: ["thử nghiệm", "16 tuần", "pilot", "các bước", "khảo sát"],
  },
  {
    id: "cong",
    q: "Các cổng nghiệm thu là gì?",
    a: "Cổng 1 (T+1): dữ liệu đủ điều kiện, thỏa thuận dữ liệu đã ký. Cổng 2 (T+4): Ứng dụng 3 báo trước ≥2 giờ cho ≥80% lần vượt hoặc tiến sát ngưỡng; Ứng dụng 1 đáp ứng 100% ràng buộc và không kém kế hoạch đã chạy; Ứng dụng 2 sai lệch trong ngưỡng đã chốt. Cổng 3 (T+8): ≥20 ca sản xuất thật có dùng dự báo, Đội ngũ IT của nhà máy Trị An tự vận hành liên tục 4 tuần. Cổng 4 (T+12): bộ phận Tài chính xác nhận giá trị ≥ ngưỡng hòa vốn. Ngưỡng cụ thể chốt sau khảo sát.",
    section: "lo-trinh",
    keywords: ["cổng", "gate", "tiêu chí", "nghiệm thu", "đánh giá"],
  },
  {
    id: "bo-de-thi",
    q: "Bộ đề thi kín hoạt động thế nào?",
    a: "Nestlé giữ riêng một phần dữ liệu lịch sử kèm kết quả thật. Mô hình làm bài trên các sự cố và kế hoạch cũ, Nestlé chấm, Celesnity không xem đáp án. Mô hình phải hơn **cả** cách làm hiện tại và một phương án tối ưu thông thường; giai đoạn nào chưa đạt thì không chuyển sang giai đoạn có phí tiếp theo.",
    section: "lo-trinh",
    keywords: ["đề thi", "bộ đề", "chấm", "kiểm chứng", "backtest", "chứng minh"],
    suggested: true,
  },
  {
    id: "khong-hon",
    q: "Nếu mô hình không hơn cách làm hiện tại thì sao?",
    a: "Celesnity báo cáo đúng kết quả đó và giữ cách làm đơn giản hơn. Ứng dụng đó dừng hoặc được điều chỉnh, và chương trình không chuyển sang giai đoạn có phí tiếp theo khi cổng chưa đạt.",
    section: "lo-trinh",
    keywords: ["không hơn", "thất bại", "không đạt", "dừng", "rủi ro"],
  },
  {
    id: "tri-an-can-lam",
    q: "Nhà máy Nestlé Trị An cần chuẩn bị những gì?",
    a: "Ba việc: **mở dữ liệu đã có** ở chế độ chỉ đọc (PLC, cảm biến môi trường, AHU, SAP/MES, cân kiểm, sổ ca, kế hoạch tuần), không thu thập công thức hay bí quyết sản xuất; **cử người**: 1 đầu mối IT/OT, Kế hoạch ~4 giờ/tuần, Sản xuất và Bảo trì ~2 giờ/tuần, QA ~1 giờ/tuần; **nhận xét, đánh giá và chấm điểm** trên bộ đề thi kín.",
    section: "use-case",
    keywords: ["chuẩn bị", "cần làm", "nhân sự", "đóng góp", "cử người"],
  },
  {
    id: "du-lieu-can",
    q: "Nhà máy cần cung cấp những dữ liệu nào?",
    a: "- Tín hiệu PLC của L1, L2: số đếm, trạng thái, mã dừng\n- Lệnh sản xuất và lượng bột cấp theo lô từ SAP/MES; dữ liệu cân kiểm viên\n- Độ ẩm, nhiệt độ từng vùng phòng chiết rót và trạng thái AHU, chiller\n- Nhật ký dừng máy, sổ ca, số liệu hao hụt đã ghi; 8–12 kế hoạch tuần gần nhất\n- Tất cả ở chế độ **chỉ đọc**; không thu thập công thức. Danh sách cuối cùng chốt trong khảo sát cùng IT/OT",
    section: "use-case",
    keywords: ["dữ liệu", "cần gì", "cung cấp", "data", "tín hiệu", "nguồn dữ liệu"],
    suggested: true,
  },
  {
    id: "khong-lam",
    q: "Giai đoạn đầu không làm những gì?",
    a: "Giai đoạn đầu **không** ghi ngược vào PLC, BMS, SAP hay MES, không điều khiển thiết bị, không đặt hay đổi ngưỡng QA, không quyết định xuất hay hủy lô, không thay dự báo nhu cầu của chuỗi cung ứng và không lập kế hoạch dài hạn. Celesnity cũng không cam kết \"không bao giờ dừng chuyền\": hỏng hóc cơ khí vẫn cần Bảo trì xử lý. Jar Line và các dây chuyền khác chỉ mở sau Cổng 3.",
    section: "use-case",
    keywords: ["không làm", "ngoài phạm vi", "giới hạn", "phạm vi", "không giải quyết"],
    suggested: true,
  },
  {
    id: "kien-truc",
    q: "Kiến trúc kỹ thuật triển khai thế nào?",
    a: "Dữ liệu từ PLC, cảm biến môi trường, AHU, SAP/MES và bảng tính kế hoạch được đọc qua historian hoặc OPC UA và gateway trong mạng OT. **Nền tảng dữ liệu** dựng bản đồ dây chuyền và lưu sự kiện; **Mô hình AI Thế giới thực** dự báo độ ẩm, hao hụt và kết quả kế hoạch; bộ giải tối ưu tạo kế hoạch; **Tác nhân AI** soạn báo cáo, cảnh báo và kế hoạch nháp để người có thẩm quyền duyệt. Hệ thống chạy trên máy chủ tại nhà máy hoặc vùng cloud Nestlé duyệt; mất kết nối thì dây chuyền vẫn chạy bình thường.",
    section: "ba-lop",
    keywords: ["kiến trúc", "kỹ thuật", "architecture", "opc ua", "historian", "gateway", "triển khai"],
  },
  {
    id: "gia-tri-do",
    q: "Giá trị kinh doanh được đo thế nào?",
    a: "Mỗi ứng dụng có chỉ số vật lý, số liệu nền, mục tiêu đề xuất và người xác nhận: giờ lập kế hoạch và giờ chuyển đổi (Ứng dụng 1), kg bột hao hụt và gram dư trên mỗi viên (Ứng dụng 2), giờ dừng vì môi trường và thời gian báo trước (Ứng dụng 3). Quy ra tiền theo đơn giá do bộ phận Tài chính Nestlé cung cấp. Celesnity **không đưa con số tiết kiệm trước khi có số liệu nền**.",
    section: "do-luong",
    keywords: ["giá trị", "roi", "đo lường", "kpi", "chỉ số", "tiết kiệm", "business value"],
    suggested: true,
  },
  {
    id: "doi-tri-an",
    q: "Đội ngũ IT của nhà máy Trị An làm chủ hệ thống như thế nào?",
    a: "Tỷ lệ vận hành chuyển dần: Celesnity 90% ở thử nghiệm, 50% ở triển khai, 20% ở nhân rộng. Đội ngũ IT của nhà máy Trị An tăng từ 1 lên 3 người và đi qua ba bậc: **vận hành** (T+4–T+8), **tự huấn luyện lại** (T+11–T+12), **dẫn dắt nhân rộng** sang nhà máy Nestlé thứ hai (năm thứ 2). IT/OT vận hành hệ thống; Kế hoạch, Sản xuất, QA xác nhận mô hình đúng về chuyên môn.",
    section: "lo-trinh",
    keywords: ["đội trị an", "đội ngũ it", "làm chủ", "chuyển giao", "tự vận hành", "năng lực"],
  },
  {
    id: "nhan-su-celesnity",
    q: "Celesnity cử bao nhiêu người?",
    a: "Theo đề xuất, khoảng 5–6 người ở thử nghiệm, 4–5 người ở triển khai và 3 người ở nhân rộng, gồm kỹ sư triển khai tại nhà máy (FDE), kỹ sư AI, kỹ sư dữ liệu và nghiên cứu. Con số chốt sau khảo sát.",
    section: "lo-trinh",
    keywords: ["bao nhiêu người", "nhân sự celesnity", "fde", "đội celesnity"],
  },
  {
    id: "nhan-rong",
    q: "Sau nhà máy Trị An sẽ mở rộng thế nào?",
    a: "Từ dây chuyền Dolce Gusto (tháng 1–8) ra toàn nhà máy Trị An (tháng 9–12): Jar Line, các dây chuyền viên nén và túi khác, khu chiết xuất và sấy, với một kế hoạch chung. Năm thứ 2 là nhà máy Nestlé thứ hai tại Việt Nam (nhà máy Nestlé Đồng Nai, Bình An hoặc Bông Sen), chọn qua khảo sát. Mỗi nhà máy có khảo sát và bộ đề thi riêng.",
    section: "ban-do",
    keywords: ["mở rộng", "nhân rộng", "nhà máy khác", "bình an", "đồng nai", "bông sen", "jar line"],
    suggested: true,
  },
  {
    id: "mang-sang",
    q: "Kinh nghiệm ở Dolce Gusto có dùng được cho nhà máy khác không?",
    a: "Những gì được nhân rộng là nền tảng, phương pháp đánh giá, bản đồ liên kết sản xuất, cách truy vết tác động và Đội ngũ IT vận hành. Độ chính xác không mặc định được nhân rộng: mỗi quy trình có mô hình riêng, mỗi nhà máy có khảo sát và bộ đề thi riêng.",
    section: "ban-do",
    keywords: ["kinh nghiệm", "mang sang", "nhân rộng", "chuyển giao", "nhà máy khác", "độ chính xác"],
  },
  {
    id: "du-lieu-roi-vn",
    q: "Dữ liệu có ra khỏi Việt Nam không?",
    a: "Dữ liệu nằm trong **môi trường Nestlé duyệt** sau đánh giá IT/OT, và không mặc định đưa ra khỏi Việt Nam. Công thức và thông số quy trình **không bao giờ rời Nestlé**. Nestlé duyệt mục đích, người truy cập, thời hạn lưu và mọi phần được chia sẻ.",
    section: "hop-tac",
    keywords: ["dữ liệu", "ra nước ngoài", "việt nam", "cloud", "bảo mật dữ liệu", "chủ quyền"],
    suggested: true,
  },
  {
    id: "ai-dieu-khien",
    q: "AI có tự điều khiển hay dừng dây chuyền không?",
    a: "Không tự ý. Mô hình **tập trung dự báo, so sánh và tối ưu hoá**; con người có thẩm quyền phê duyệt mọi thay đổi. Interlock, bảo vệ an toàn, thông số đã thẩm định và quyết định QA giữ nguyên quyền hiện tại. Tự động hoá bằng AI đi theo từng bước; mỗi bước lên mức tự chủ cao hơn là quyết định riêng của Nestlé, qua quy trình quản lý thay đổi.",
    section: "hop-tac",
    keywords: ["điều khiển", "tự động", "dừng dây chuyền", "plc", "an toàn", "interlock", "tự chủ"],
  },
  {
    id: "an-toan-thuc-pham",
    q: "An toàn thực phẩm được đảm bảo thế nào?",
    a: "HACCP và hệ thống chất lượng của Nestlé là một lớp riêng; báo cáo AI không thay thế được. Thử nghiệm đầu tiên không đụng tới thông số an toàn thực phẩm, chu trình vệ sinh đã thẩm định, quy tắc chuyển đổi liên quan đến chất gây dị ứng, thay nguyên liệu hay quyết định xuất, hủy lô.",
    section: "hop-tac",
    keywords: ["an toàn thực phẩm", "haccp", "vệ sinh", "dị ứng", "food safety"],
  },
  {
    id: "an-ninh",
    q: "An ninh hệ thống được thiết kế thế nào?",
    a: "Theo kiến trúc nhà máy đã duyệt, tham chiếu IEC 62443 và NIST SP 800-82; bắt đầu ở chế độ chỉ đọc; ghi nhật ký mọi lần gọi mô hình. Khi mất kết nối, nhà máy vẫn chạy bình thường qua hệ thống hiện có.",
    section: "hop-tac",
    keywords: ["an ninh", "bảo mật", "iec 62443", "nist", "mất kết nối", "cyber"],
  },
  {
    id: "so-huu",
    q: "Ai sở hữu mô hình và dữ liệu?",
    a: "Nestlé toàn quyền với dữ liệu vận hành, công thức và hồ sơ nhà máy, và sở hữu mô hình riêng cùng các kết quả về hoạt động của nhà máy Trị An. Celesnity sở hữu mô hình nền, mã huấn luyện và bộ công cụ đánh giá; Nestlé có giấy phép nội bộ vĩnh viễn, miễn phí bản quyền. Khi chấm dứt hợp tác, Nestlé giữ mô hình riêng và giấy phép.",
    section: "hop-tac",
    keywords: ["sở hữu", "sở hữu trí tuệ", "ip", "mô hình riêng", "giấy phép"],
  },
  {
    id: "chi-phi",
    q: "Chi phí thử nghiệm là bao nhiêu?",
    a: "Phí thử nghiệm là **phí cố định**, thống nhất sau khảo sát dây chuyền NESCAFÉ Dolce Gusto. Sau thử nghiệm, định giá theo giá trị bộ phận Tài chính Nestlé đã xác minh; mỗi dây chuyền, mỗi nhà máy theo phạm vi riêng. Không đạt Cổng 2 thì không chuyển sang giai đoạn có phí tiếp theo.",
    section: "hop-tac",
    keywords: ["chi phí", "giá", "phí", "bao nhiêu tiền", "báo giá", "ngân sách"],
  },
  {
    id: "loi-ich",
    q: "Hai bên nhận và góp những gì?",
    a: "Nhà máy Nestlé Trị An nhận giá trị đo được trên dây chuyền, mô hình riêng trong môi trường Nestlé duyệt, Đội ngũ IT của nhà máy Trị An tự vận hành và huấn luyện lại, cùng con đường mở rộng; nhà máy góp dữ liệu chỉ đọc trong phạm vi Nestlé duyệt, chuyên gia và Đội ngũ IT của nhà máy Trị An 1→3 người. Celesnity nhận mô hình được kiểm chứng trong sản xuất thực phẩm và đối tác tham chiếu khi Nestlé đồng ý; Celesnity góp mô hình nền, nền tảng dữ liệu và đội kỹ sư triển khai tại nhà máy (FDE).",
    section: "hai-ben",
    keywords: ["lợi ích", "hai bên", "nhận", "góp", "đối tác"],
  },
  {
    id: "buoc-tiep-theo",
    q: "Bước tiếp theo là gì?",
    a: "Celesnity kính đề nghị Ban Giám đốc: thống nhất định hướng để nhà máy Nestlé Trị An tham gia với vai trò Đối tác công nghiệp sáng lập, với dây chuyền Dolce Gusto là điểm khởi đầu; cử đầu mối Sản xuất, Kế hoạch, QA, IT/OT, Tài chính; và cho phép khảo sát dây chuyền để chốt danh sách dữ liệu, số liệu nền, mục tiêu của từng ứng dụng và phí thử nghiệm. Tại buổi làm việc ở nhà máy, hai bên đi qua ba ứng dụng trên dây chuyền thật.",
    section: "thu-ngo",
    keywords: ["bước tiếp theo", "đề nghị", "bắt đầu", "khảo sát", "next step", "buổi làm việc"],
  },
];
