/**
 * Câu hỏi thường gặp của deck Nestlé Trị An, chỉ lấy từ nội dung đề xuất (decks/nestle-vietnam/content.vi.ts).
 * Dùng cho: gói tri thức của trợ lý Nestlé, câu trả lời soạn sẵn khi offline / hết ngân sách / lỗi API, và câu gợi ý.
 * Không chứa thông tin của khách hàng khác. `keywords` viết có dấu hoặc không đều được.
 */
import type { FaqItem } from "../types";

export const faq: FaqItem[] = [
  {
    id: "nha-may-sieu-thong-minh-la-gi",
    q: "Nhà máy siêu thông minh là gì?",
    a: "Đó là nhà máy mà kế hoạch, vận hành và phục hồi chạy trên cùng một **Mô hình AI Thế giới thực**. Nhà máy **tự học** từ mỗi kế hoạch và kết quả, **dự báo trước** hệ quả của một quyết định trước khi làm, và **nhân rộng** kinh nghiệm sang dây chuyền và nhà máy khác. Con người luôn là người quyết định.",
    section: "sieu-thong-minh",
    keywords: ["siêu thông minh", "là gì", "định nghĩa", "tự học", "dự báo trước", "nhân rộng"],
    suggested: true,
  },
  {
    id: "vi-sao-dolce-gusto",
    q: "Vì sao bắt đầu từ dây chuyền NESCAFÉ Dolce Gusto?",
    a: "Một dây chuyền viên nén có đủ các loại quyết định: kế hoạch, chuyển đổi SKU, môi trường phòng kiểm soát, chất lượng và đóng gói. Dây chuyền hiện đại nên phần lớn thời gian thử nghiệm dành cho bài toán, không cho lắp đặt. Sản phẩm xuất khẩu nên kết quả đo được bằng đơn vị rõ ràng.",
    section: "ban-do",
    keywords: ["dolce gusto", "bắt đầu", "vì sao", "dây chuyền đầu tiên", "viên nén"],
    suggested: true,
  },
  {
    id: "thay-the-he-thong",
    q: "Celesnity có thay thế MES, SAP hay SCADA không?",
    a: "Không. Celesnity **không thay thế bất kỳ hệ thống nào đang vận hành**. Mô hình đọc dữ liệu (chỉ đọc) từ chính các hệ thống hiện có của nhà máy Nestlé Trị An và trả lời những câu hỏi mà từng hệ thống riêng lẻ chưa trả lời được: một sự việc ảnh hưởng thế nào đến lô, kế hoạch, đơn hàng, và bước xử lý tiếp theo nên là gì.",
    section: "hai-con-duong",
    keywords: ["mes", "sap", "scada", "thay thế", "hệ thống hiện có", "historian", "tích hợp"],
    suggested: true,
  },
  {
    id: "khac-cong-cu-ai",
    q: "Khác gì so với việc thêm từng công cụ AI riêng lẻ?",
    a: "Mỗi công cụ riêng chỉ thấy một phần của nhà máy, nên một cảnh báo độ ẩm chỉ dừng lại trong công cụ cảnh báo. Một mô hình chung thấy toàn bộ bức tranh sản xuất, nên cùng cảnh báo đó được truy tới lô và mẻ, tính tác động lên kế hoạch và đơn hàng, và có sẵn các phương án phục hồi.",
    section: "hai-con-duong",
    keywords: ["công cụ riêng lẻ", "khác gì", "dashboard", "cảnh báo", "một mô hình chung"],
  },
  {
    id: "mo-hinh-the-gioi-thuc",
    q: "Mô hình AI Thế giới thực khác chatbot như thế nào?",
    a: "Chatbot đọc và trả lời từ tài liệu. **Mô hình AI Thế giới thực** học cách dây chuyền phản ứng với quyết định và sự cố, rồi dự báo hệ quả của một phương án trước khi làm, kèm mức độ chắc chắn. Mô hình nói \"chưa đủ dữ liệu\" khi gặp tình huống chưa có dữ liệu, không bịa ra kết quả.",
    section: "ba-lop",
    keywords: ["world model", "chatbot", "mô hình ai thế giới thực", "khác gì", "llm"],
  },
  {
    id: "ba-lop",
    q: "Hệ thống gồm những lớp nào?",
    a: "Ba lớp: **Nền tảng dữ liệu** ghi lại và đồng bộ dữ liệu từ MES, historian, ERP, QMS, bảo trì; **Mô hình AI Thế giới thực** dự báo; **Tác nhân AI** soạn kế hoạch, truy vết và phương án. Con người có thẩm quyền phê duyệt mọi kế hoạch, phương án và quyết định chất lượng.",
    section: "ba-lop",
    keywords: ["ba lớp", "kiến trúc", "tác nhân ai", "nền tảng dữ liệu", "agent"],
  },
  {
    id: "lich-san-xuat-llm",
    q: "Ai tạo ra lịch sản xuất, mô hình ngôn ngữ hay bộ giải?",
    a: "Lịch sản xuất do **bộ giải tối ưu có ràng buộc** tạo ra, và mọi phương án vi phạm ràng buộc bắt buộc đều bị loại. Mô hình dự báo kết quả của từng lịch. Mô hình ngôn ngữ chỉ hiểu câu hỏi và giải thích kết quả, **không tự nghĩ ra lịch**. Bộ phận Kế hoạch là người duyệt.",
    section: "use-case",
    keywords: ["lịch sản xuất", "bộ giải", "solver", "tối ưu", "kế hoạch tuần", "llm"],
  },
  {
    id: "su-co-do-am",
    q: "Khi độ ẩm phòng kiểm soát vượt giới hạn, hệ thống làm gì?",
    a: "Trong tình huống minh họa, AI tự mở hồ sơ sự cố, gắn phòng, thời gian, lô bột và mẻ. Mô hình đối chiếu quy tắc chất lượng của nhà máy, rồi tính tác động: giờ không sản xuất được, sản lượng còn thiếu, chuyển đổi bị trễ, đơn hàng có thể bị ảnh hưởng. Tác nhân AI soạn bốn phương án phục hồi; QA quyết định về lô và Trưởng phòng Sản xuất duyệt phương án.",
    section: "thu-ngay",
    keywords: ["độ ẩm", "phòng kiểm soát", "sự cố", "humidity", "phục hồi", "lô bị ảnh hưởng"],
    suggested: true,
  },
  {
    id: "nguong-ai-dat",
    q: "Ngưỡng độ ẩm và quyết định xử lý lô có do AI đặt không?",
    a: "Không. Ngưỡng, giới hạn và quy tắc xử lý lấy từ **tiêu chuẩn của nhà máy**. Quyết định QA và xuất lô giữ nguyên quyền hiện tại; mô hình chỉ nêu bằng chứng và đề xuất.",
    section: "thu-ngay",
    keywords: ["ngưỡng", "qa", "xuất lô", "quyết định lô", "tiêu chuẩn nhà máy"],
  },
  {
    id: "sau-ung-dung",
    q: "Sáu ứng dụng gồm những gì?",
    a: "- Ứng dụng 01: báo cáo ca tự động (T+1)\n- Ứng dụng 02: truy vết sự cố môi trường (T+5)\n- Ứng dụng 03: kế hoạch sản xuất và phục hồi (T+6)\n- Ứng dụng 04 và 05: định lượng chiết rót; dừng máy, điểm nghẽn và chuyển đổi (T+7, T+8)\n- Ứng dụng 06: sẵn sàng sản xuất và cửa sổ bảo trì (T+9)",
    section: "use-case",
    keywords: ["ứng dụng", "use case", "sáu ứng dụng", "danh mục"],
    suggested: true,
  },
  {
    id: "dinh-luong",
    q: "Ứng dụng định lượng chiết rót giúp gì?",
    a: "Ứng dụng 04 theo dõi xu hướng định lượng theo lô bột, SKU và điều kiện môi trường, rồi đề xuất điều chỉnh trong giới hạn đã duyệt. Mục tiêu là giảm lượng cà phê dư trên mỗi viên mà **vẫn đạt khối lượng tịnh**; Sản xuất và QA quyết định.",
    section: "use-case",
    keywords: ["định lượng", "giveaway", "lượng dư", "khối lượng tịnh", "chiết rót", "cân kiểm tra"],
  },
  {
    id: "bao-tri-du-doan",
    q: "Có phải là bảo trì dự đoán không?",
    a: "Ứng dụng 06 không thay hệ thống giám sát thiết bị hiện có. Nó dùng cảnh báo từ các hệ thống đó để chọn cửa sổ bảo trì ít ảnh hưởng nhất đến sản lượng, đơn hàng, nhân lực và phụ tùng. Bảo trì và Kế hoạch là người quyết định.",
    section: "use-case",
    keywords: ["bảo trì", "predictive maintenance", "bảo trì dự đoán", "cửa sổ bảo trì", "giám sát thiết bị"],
  },
  {
    id: "lo-trinh-12-thang",
    q: "Lộ trình 12 tháng diễn ra thế nào?",
    a: "Bốn giai đoạn: **Thử nghiệm** (T+1–T+4) trên dây chuyền Dolce Gusto với bộ đề thi kín; **Triển khai** (T+5–T+8) dùng dự báo cho quyết định thật; **Nhân rộng** (T+9–T+12) ra toàn nhà máy Trị An với một kế hoạch chung; **Năm thứ 2**, Đội ngũ IT của nhà máy Trị An dẫn dắt nhân rộng sang nhà máy Nestlé thứ hai.",
    section: "lo-trinh",
    keywords: ["lộ trình", "12 tháng", "giai đoạn", "timeline", "kế hoạch triển khai"],
    suggested: true,
  },
  {
    id: "thu-nghiem-16-tuan",
    q: "Thử nghiệm 16 tuần gồm những bước nào?",
    a: "Tuần 1–2 khảo sát và chốt bài toán; tuần 3–4 dựng môi trường, kết nối chỉ đọc và bật Ứng dụng 01 (Cổng 1); tuần 5–8 nối dữ liệu lịch sử, Nestlé dựng bộ đề thi kín; tuần 9–12 thi trên dữ liệu lịch sử của nhà máy Trị An; tuần 13–14 chạy song song trên ca thật; tuần 15–16 bộ phận Tài chính xác nhận cách đo giá trị (Cổng 2).",
    section: "lo-trinh",
    keywords: ["thử nghiệm", "16 tuần", "pilot", "các bước", "khảo sát"],
  },
  {
    id: "cong",
    q: "Các cổng nghiệm thu là gì?",
    a: "Cổng 1 (T+1): dữ liệu đủ điều kiện để triển khai, thỏa thuận dữ liệu đã ký. Cổng 2 (T+4): truy vết đúng lô ở ≥95% sự cố đã xảy ra, lịch đề xuất đáp ứng 100% ràng buộc bắt buộc và không kém kế hoạch đã áp dụng. Cổng 3 (T+8): ≥20 ca sản xuất thật có dùng dự báo, Đội ngũ IT của nhà máy Trị An tự vận hành liên tục 4 tuần. Cổng 4 (T+12): bộ phận Tài chính xác nhận giá trị ≥ ngưỡng hòa vốn. Ngưỡng cụ thể chốt sau khảo sát.",
    section: "lo-trinh",
    keywords: ["cổng", "gate", "tiêu chí", "nghiệm thu", "đánh giá"],
  },
  {
    id: "bo-de-thi",
    q: "Bộ đề thi kín hoạt động thế nào?",
    a: "Nestlé giữ riêng một phần dữ liệu lịch sử kèm kết quả thật. Mô hình làm bài trên các sự cố và kế hoạch cũ, Nestlé chấm, Celesnity không xem đáp án. Mô hình phải hơn **cả** cách làm hiện tại và một phương án tối ưu thông thường; giai đoạn nào chưa đạt thì không chuyển sang giai đoạn có phí tiếp theo.",
    section: "lo-trinh",
    keywords: ["đề thi", "bộ đề", "chấm", "kiểm chứng", "backtest", "chứng minh"],
    suggested: true,
  },
  {
    id: "khong-hon",
    q: "Nếu mô hình không hơn cách làm hiện tại thì sao?",
    a: "Celesnity báo cáo đúng kết quả đó và giữ cách làm đơn giản hơn. Ứng dụng đó dừng hoặc được điều chỉnh, và chương trình không chuyển sang giai đoạn có phí tiếp theo khi cổng chưa đạt.",
    section: "lo-trinh",
    keywords: ["không hơn", "thất bại", "không đạt", "dừng", "rủi ro"],
  },
  {
    id: "tri-an-can-lam",
    q: "Nhà máy Nestlé Trị An cần chuẩn bị những gì?",
    a: "Ba việc: **mở dữ liệu đã có** ở chế độ chỉ đọc, không thu thập công thức hay bí quyết sản xuất, không làm gián đoạn hệ thống hiện tại; **cử người**: 1 đầu mối IT/OT cho Đội ngũ IT của nhà máy Trị An, chuyên gia Kế hoạch và Sản xuất khoảng 4 giờ/tuần; **nhận xét, đánh giá và chấm điểm** trên bộ đề thi kín.",
    section: "lo-trinh",
    keywords: ["chuẩn bị", "cần làm", "nhân sự", "đóng góp", "cử người"],
  },
  {
    id: "doi-tri-an",
    q: "Đội ngũ IT của nhà máy Trị An làm chủ hệ thống như thế nào?",
    a: "Tỷ lệ vận hành chuyển dần: Celesnity 90% ở thử nghiệm, 50% ở triển khai, 20% ở nhân rộng. Đội ngũ IT của nhà máy Trị An tăng từ 1 lên 3 người và đi qua ba bậc: **vận hành** (T+4–T+8), **tự huấn luyện lại** (T+11–T+12), **dẫn dắt nhân rộng** sang nhà máy Nestlé thứ hai (năm thứ 2). IT/OT vận hành hệ thống; Kế hoạch, Sản xuất, QA xác nhận mô hình đúng về chuyên môn.",
    section: "lo-trinh",
    keywords: ["đội trị an", "đội ngũ it", "làm chủ", "chuyển giao", "tự vận hành", "năng lực"],
  },
  {
    id: "nhan-su-celesnity",
    q: "Celesnity cử bao nhiêu người?",
    a: "Theo đề xuất, khoảng 5–6 người ở thử nghiệm, 4–5 người ở triển khai và 3 người ở nhân rộng, gồm kỹ sư triển khai tại nhà máy (FDE), kỹ sư AI, kỹ sư dữ liệu và nghiên cứu. Con số chốt sau khảo sát.",
    section: "lo-trinh",
    keywords: ["bao nhiêu người", "nhân sự celesnity", "fde", "đội celesnity"],
  },
  {
    id: "nhan-rong",
    q: "Sau nhà máy Trị An sẽ mở rộng thế nào?",
    a: "Từ dây chuyền Dolce Gusto (tháng 1–8) ra toàn nhà máy Trị An (tháng 9–12): Jar Line, các dây chuyền viên nén và túi khác, khu chiết xuất và sấy, với một kế hoạch chung. Năm thứ 2 là nhà máy Nestlé thứ hai tại Việt Nam (nhà máy Nestlé Đồng Nai, Bình An hoặc Bông Sen), chọn qua khảo sát. Mỗi nhà máy có khảo sát và bộ đề thi riêng.",
    section: "ban-do",
    keywords: ["mở rộng", "nhân rộng", "nhà máy khác", "bình an", "đồng nai", "bông sen", "jar line"],
    suggested: true,
  },
  {
    id: "mang-sang",
    q: "Kinh nghiệm ở Dolce Gusto có dùng được cho nhà máy khác không?",
    a: "Những gì được nhân rộng là nền tảng, phương pháp đánh giá, bản đồ liên kết sản xuất, cách truy vết tác động và Đội ngũ IT vận hành. Độ chính xác không mặc định được nhân rộng: mỗi quy trình có mô hình riêng, mỗi nhà máy có khảo sát và bộ đề thi riêng.",
    section: "ban-do",
    keywords: ["kinh nghiệm", "mang sang", "nhân rộng", "chuyển giao", "nhà máy khác", "độ chính xác"],
  },
  {
    id: "du-lieu-roi-vn",
    q: "Dữ liệu có ra khỏi Việt Nam không?",
    a: "Dữ liệu nằm trong **môi trường Nestlé duyệt** sau đánh giá IT/OT, và không mặc định đưa ra khỏi Việt Nam. Công thức và thông số quy trình **không bao giờ rời Nestlé**. Nestlé duyệt mục đích, người truy cập, thời hạn lưu và mọi phần được chia sẻ.",
    section: "hop-tac",
    keywords: ["dữ liệu", "ra nước ngoài", "việt nam", "cloud", "bảo mật dữ liệu", "chủ quyền"],
    suggested: true,
  },
  {
    id: "ai-dieu-khien",
    q: "AI có tự điều khiển hay dừng dây chuyền không?",
    a: "Không tự ý. Mô hình **tập trung dự báo, so sánh và tối ưu hoá**; con người có thẩm quyền phê duyệt mọi thay đổi. Interlock, bảo vệ an toàn, thông số đã thẩm định và quyết định QA giữ nguyên quyền hiện tại. Tự động hoá bằng AI đi theo từng bước; mỗi bước lên mức tự chủ cao hơn là quyết định riêng của Nestlé, qua quy trình quản lý thay đổi.",
    section: "hop-tac",
    keywords: ["điều khiển", "tự động", "dừng dây chuyền", "plc", "an toàn", "interlock", "tự chủ"],
  },
  {
    id: "an-toan-thuc-pham",
    q: "An toàn thực phẩm được đảm bảo thế nào?",
    a: "HACCP và hệ thống chất lượng của Nestlé là một lớp riêng; báo cáo AI không thay thế được. Thử nghiệm đầu tiên không đụng tới thông số an toàn thực phẩm, chu trình vệ sinh đã thẩm định, quy tắc chuyển đổi liên quan đến chất gây dị ứng, thay nguyên liệu hay quyết định xuất, hủy lô.",
    section: "hop-tac",
    keywords: ["an toàn thực phẩm", "haccp", "vệ sinh", "dị ứng", "food safety"],
  },
  {
    id: "an-ninh",
    q: "An ninh hệ thống được thiết kế thế nào?",
    a: "Theo kiến trúc nhà máy đã duyệt, tham chiếu IEC 62443 và NIST SP 800-82; bắt đầu ở chế độ chỉ đọc; ghi nhật ký mọi lần gọi mô hình. Khi mất kết nối, nhà máy vẫn chạy bình thường qua hệ thống hiện có.",
    section: "hop-tac",
    keywords: ["an ninh", "bảo mật", "iec 62443", "nist", "mất kết nối", "cyber"],
  },
  {
    id: "so-huu",
    q: "Ai sở hữu mô hình và dữ liệu?",
    a: "Nestlé toàn quyền với dữ liệu vận hành, công thức và hồ sơ nhà máy, và sở hữu mô hình riêng cùng các kết quả về hoạt động của nhà máy Trị An. Celesnity sở hữu mô hình nền, mã huấn luyện và bộ công cụ đánh giá; Nestlé có giấy phép nội bộ vĩnh viễn, miễn phí bản quyền. Khi chấm dứt hợp tác, Nestlé giữ mô hình riêng và giấy phép.",
    section: "hop-tac",
    keywords: ["sở hữu", "sở hữu trí tuệ", "ip", "mô hình riêng", "giấy phép"],
  },
  {
    id: "chi-phi",
    q: "Chi phí thử nghiệm là bao nhiêu?",
    a: "Phí thử nghiệm là **phí cố định**, thống nhất sau khảo sát dây chuyền NESCAFÉ Dolce Gusto. Sau thử nghiệm, định giá theo giá trị bộ phận Tài chính Nestlé đã xác minh; mỗi dây chuyền, mỗi nhà máy theo phạm vi riêng. Không đạt Cổng 2 thì không chuyển sang giai đoạn có phí tiếp theo.",
    section: "hop-tac",
    keywords: ["chi phí", "giá", "phí", "bao nhiêu tiền", "báo giá", "ngân sách"],
  },
  {
    id: "loi-ich",
    q: "Hai bên nhận và góp những gì?",
    a: "Nhà máy Nestlé Trị An nhận giá trị đo được trên dây chuyền, mô hình riêng trong môi trường Nestlé duyệt, Đội ngũ IT của nhà máy Trị An tự vận hành và huấn luyện lại, cùng con đường mở rộng; nhà máy góp dữ liệu chỉ đọc trong phạm vi Nestlé duyệt, chuyên gia và Đội ngũ IT của nhà máy Trị An 1→3 người. Celesnity nhận mô hình được kiểm chứng trong sản xuất thực phẩm và đối tác tham chiếu khi Nestlé đồng ý; Celesnity góp mô hình nền, nền tảng dữ liệu và đội kỹ sư triển khai tại nhà máy (FDE).",
    section: "hai-ben",
    keywords: ["lợi ích", "hai bên", "nhận", "góp", "đối tác"],
  },
  {
    id: "buoc-tiep-theo",
    q: "Bước tiếp theo là gì?",
    a: "Celesnity kính đề nghị Ban Giám đốc: thống nhất định hướng để nhà máy Nestlé Trị An tham gia với vai trò Đối tác công nghiệp sáng lập, với dây chuyền Dolce Gusto là điểm khởi đầu; cử đầu mối Sản xuất, Kế hoạch, QA, IT/OT, Tài chính và 1 đầu mối IT/OT cho Đội ngũ IT của nhà máy Trị An; và cho phép khảo sát dây chuyền để chốt bài toán, số liệu nền và phí thử nghiệm.",
    section: "thu-ngo",
    keywords: ["bước tiếp theo", "đề nghị", "bắt đầu", "khảo sát", "next step"],
  },
];
